name: Reusable Workflow

on:
  workflow_call:
    inputs:
      greeting:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run a script
      run: echo "Hello, world!"
